/**
 * Migration: Add Referral System Tables
 *
 * This migration adds the database tables needed for the
 * viral growth referral program:
 *
 * - referral_codes: Stores user-generated referral codes
 * - referral_redemptions: Tracks when codes are used
 * - department_challenges: Gamification campaigns for departments
 * - challenge_scores: Leaderboard tracking
 */

import { int, mysqlEnum, mysqlTable, text, timestamp, varchar, boolean, json, decimal } from "drizzle-orm/mysql-core";

// ============ Referral System Tables ============

/**
 * Referral codes generated by users to share with their crew
 */
export const referralCodes = mysqlTable("referral_codes", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(), // Owner of this referral code
  code: varchar("code", { length: 12 }).notNull().unique(), // e.g., "CREW-A3B7C9"
  usesCount: int("usesCount").default(0).notNull(),
  maxUses: int("maxUses"), // null = unlimited
  rewardType: mysqlEnum("rewardType", ["pro_days", "credits", "department_discount"]).default("pro_days"),
  rewardAmount: int("rewardAmount").default(7).notNull(), // days or credit amount
  campaignId: int("campaignId"), // Optional: link to specific campaign
  expiresAt: timestamp("expiresAt"),
  isActive: boolean("isActive").default(true).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type ReferralCode = typeof referralCodes.$inferSelect;
export type InsertReferralCode = typeof referralCodes.$inferInsert;

/**
 * Tracks when referral codes are redeemed
 */
export const referralRedemptions = mysqlTable("referral_redemptions", {
  id: int("id").autoincrement().primaryKey(),
  referralCodeId: int("referralCodeId").notNull(),
  referredUserId: int("referredUserId").notNull(), // New user who used code
  referrerUserId: int("referrerUserId").notNull(), // Code owner
  referrerReward: json("referrerReward").$type<{
    type: "pro_days" | "credits";
    amount: number;
    applied: boolean;
  }>(),
  refereeReward: json("refereeReward").$type<{
    type: "pro_days" | "credits" | "extended_trial";
    amount: number;
    applied: boolean;
  }>(),
  redeemedAt: timestamp("redeemedAt").defaultNow().notNull(),
  // Track if this referral converts to paid
  convertedToPaid: boolean("convertedToPaid").default(false),
  conversionDate: timestamp("conversionDate"),
  attributedRevenue: decimal("attributedRevenue", { precision: 10, scale: 2 }),
});

export type ReferralRedemption = typeof referralRedemptions.$inferSelect;
export type InsertReferralRedemption = typeof referralRedemptions.$inferInsert;

/**
 * Referral milestones and tiers for gamification
 */
export const referralMilestones = mysqlTable("referral_milestones", {
  id: int("id").autoincrement().primaryKey(),
  name: varchar("name", { length: 100 }).notNull(), // e.g., "First Referral", "Super Ambassador"
  requiredReferrals: int("requiredReferrals").notNull(),
  rewardType: mysqlEnum("rewardType", ["pro_days", "credits", "badge", "merchandise"]).notNull(),
  rewardAmount: int("rewardAmount"), // null for badges/merch
  rewardDescription: varchar("rewardDescription", { length: 255 }),
  badgeIcon: varchar("badgeIcon", { length: 100 }), // Icon name or URL
  isActive: boolean("isActive").default(true).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type ReferralMilestone = typeof referralMilestones.$inferSelect;
export type InsertReferralMilestone = typeof referralMilestones.$inferInsert;

/**
 * Track which milestones users have achieved
 */
export const userReferralMilestones = mysqlTable("user_referral_milestones", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  milestoneId: int("milestoneId").notNull(),
  achievedAt: timestamp("achievedAt").defaultNow().notNull(),
  rewardClaimed: boolean("rewardClaimed").default(false),
  rewardClaimedAt: timestamp("rewardClaimedAt"),
});

export type UserReferralMilestone = typeof userReferralMilestones.$inferSelect;
export type InsertUserReferralMilestone = typeof userReferralMilestones.$inferInsert;

// ============ Department Challenge Tables ============

/**
 * Scoring configuration for challenges
 */
export interface ChallengeScoring {
  dailyActiveUser: number;      // Points per DAU
  searchCompleted: number;      // Points per search
  newUserOnboarded: number;     // Points per new signup
  feedbackSubmitted: number;    // Points per feedback
  protocolBookmarked: number;   // Points per bookmark
}

/**
 * Score breakdown by category
 */
export interface ScoreBreakdown {
  dauPoints: number;
  searchPoints: number;
  onboardingPoints: number;
  feedbackPoints: number;
  bookmarkPoints: number;
  bonusPoints: number;
}

/**
 * Department-wide challenges/competitions
 */
export const departmentChallenges = mysqlTable("department_challenges", {
  id: int("id").autoincrement().primaryKey(),
  name: varchar("name", { length: 255 }).notNull(),
  description: text("description"),
  startDate: timestamp("startDate").notNull(),
  endDate: timestamp("endDate").notNull(),
  minParticipants: int("minParticipants").default(10), // Minimum users to qualify
  prizeDescription: text("prizeDescription"),
  prizes: json("prizes").$type<{
    first: string;
    second?: string;
    third?: string;
    participation?: string;
  }>(),
  scoringConfig: json("scoringConfig").$type<ChallengeScoring>(),
  status: mysqlEnum("status", ["upcoming", "active", "ended", "cancelled"]).default("upcoming"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  createdBy: int("createdBy").notNull(),
});

export type DepartmentChallenge = typeof departmentChallenges.$inferSelect;
export type InsertDepartmentChallenge = typeof departmentChallenges.$inferInsert;

/**
 * Department scores in active challenges
 */
export const challengeScores = mysqlTable("challenge_scores", {
  id: int("id").autoincrement().primaryKey(),
  challengeId: int("challengeId").notNull(),
  agencyId: int("agencyId").notNull(),
  score: int("score").default(0).notNull(),
  rank: int("rank"), // Calculated position
  breakdown: json("breakdown").$type<ScoreBreakdown>(),
  participantCount: int("participantCount").default(0), // Active users in department
  lastUpdated: timestamp("lastUpdated").defaultNow().onUpdateNow().notNull(),
});

export type ChallengeScore = typeof challengeScores.$inferSelect;
export type InsertChallengeScore = typeof challengeScores.$inferInsert;

/**
 * Challenge participation registration
 */
export const challengeParticipants = mysqlTable("challenge_participants", {
  id: int("id").autoincrement().primaryKey(),
  challengeId: int("challengeId").notNull(),
  agencyId: int("agencyId").notNull(),
  registeredBy: int("registeredBy").notNull(), // User who registered department
  registeredAt: timestamp("registeredAt").defaultNow().notNull(),
  status: mysqlEnum("status", ["registered", "active", "disqualified", "winner"]).default("registered"),
  prizeAwarded: varchar("prizeAwarded", { length: 255 }),
  prizeAwardedAt: timestamp("prizeAwardedAt"),
});

export type ChallengeParticipant = typeof challengeParticipants.$inferSelect;
export type InsertChallengeParticipant = typeof challengeParticipants.$inferInsert;

// ============ Growth Campaign Tables ============

/**
 * Marketing campaigns for tracking referral sources
 */
export const growthCampaigns = mysqlTable("growth_campaigns", {
  id: int("id").autoincrement().primaryKey(),
  name: varchar("name", { length: 255 }).notNull(),
  type: mysqlEnum("type", [
    "referral",
    "ambassador",
    "conference",
    "podcast",
    "union_partnership",
    "student_program",
    "ems_week",
    "other",
  ]).notNull(),
  description: text("description"),
  utmSource: varchar("utmSource", { length: 100 }),
  utmMedium: varchar("utmMedium", { length: 100 }),
  utmCampaign: varchar("utmCampaign", { length: 100 }),
  startDate: timestamp("startDate"),
  endDate: timestamp("endDate"),
  budget: decimal("budget", { precision: 10, scale: 2 }),
  targetSignups: int("targetSignups"),
  actualSignups: int("actualSignups").default(0),
  targetConversions: int("targetConversions"),
  actualConversions: int("actualConversions").default(0),
  status: mysqlEnum("status", ["draft", "active", "paused", "ended"]).default("draft"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  createdBy: int("createdBy"),
});

export type GrowthCampaign = typeof growthCampaigns.$inferSelect;
export type InsertGrowthCampaign = typeof growthCampaigns.$inferInsert;

/**
 * Student ambassadors program
 */
export const studentAmbassadors = mysqlTable("student_ambassadors", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  schoolName: varchar("schoolName", { length: 255 }).notNull(),
  programType: mysqlEnum("programType", ["emt_basic", "emt_advanced", "paramedic", "other"]).notNull(),
  expectedGraduation: varchar("expectedGraduation", { length: 7 }), // YYYY-MM format
  referralCodeId: int("referralCodeId"), // Their ambassador referral code
  status: mysqlEnum("status", ["applied", "approved", "active", "inactive", "graduated"]).default("applied"),
  signupsGenerated: int("signupsGenerated").default(0),
  conversionsGenerated: int("conversionsGenerated").default(0),
  totalEarnings: decimal("totalEarnings", { precision: 10, scale: 2 }).default("0"),
  lastActivityAt: timestamp("lastActivityAt"),
  appliedAt: timestamp("appliedAt").defaultNow().notNull(),
  approvedAt: timestamp("approvedAt"),
  graduatedAt: timestamp("graduatedAt"),
});

export type StudentAmbassador = typeof studentAmbassadors.$inferSelect;
export type InsertStudentAmbassador = typeof studentAmbassadors.$inferInsert;

// ============ Viral Tracking Tables ============

/**
 * Track viral actions for analytics
 */
export const viralEvents = mysqlTable("viral_events", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId"),
  eventType: mysqlEnum("eventType", [
    "referral_code_generated",
    "referral_code_shared",
    "referral_code_copied",
    "share_button_tapped",
    "shift_share_shown",
    "shift_share_accepted",
    "shift_share_dismissed",
    "social_share_completed",
    "qr_code_scanned",
    "magic_link_clicked",
  ]).notNull(),
  metadata: json("metadata").$type<{
    shareMethod?: "sms" | "whatsapp" | "email" | "copy" | "qr";
    referralCode?: string;
    campaignId?: number;
    platform?: string;
    source?: string;
  }>(),
  sessionId: varchar("sessionId", { length: 64 }),
  ipAddress: varchar("ipAddress", { length: 45 }),
  userAgent: varchar("userAgent", { length: 500 }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type ViralEvent = typeof viralEvents.$inferSelect;
export type InsertViralEvent = typeof viralEvents.$inferInsert;

/**
 * User referral statistics (denormalized for fast dashboard queries)
 */
export const userReferralStats = mysqlTable("user_referral_stats", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull().unique(),
  totalReferrals: int("totalReferrals").default(0).notNull(),
  successfulReferrals: int("successfulReferrals").default(0).notNull(), // Converted to paid
  pendingReferrals: int("pendingReferrals").default(0).notNull(),
  proDaysEarned: int("proDaysEarned").default(0).notNull(),
  creditsEarned: int("creditsEarned").default(0).notNull(),
  revenueAttributed: decimal("revenueAttributed", { precision: 10, scale: 2 }).default("0"),
  currentTier: mysqlEnum("currentTier", ["bronze", "silver", "gold", "platinum", "ambassador"]).default("bronze"),
  rank: int("rank"), // Leaderboard position
  lastReferralAt: timestamp("lastReferralAt"),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type UserReferralStats = typeof userReferralStats.$inferSelect;
export type InsertUserReferralStats = typeof userReferralStats.$inferInsert;
