/**
 * LA County EMS Hospital Directory - Central Region
 *
 * Hospitals in the Central geographic region of LA County.
 * Used for MCI assignments and destination routing.
 *
 * Reference: LA County EMS Agency Ref 501 - Hospital Directory
 */

import type { Facility } from "../types";

/**
 * Central region hospitals.
 */
export const CENTRAL_HOSPITALS: Facility[] = [
  {
    id: "WMH",
    name: "Adventist Health White Memorial",
    shortName: "Adventist White Memorial",
    address: "1720 Caesar Chavez Avenue, Los Angeles, CA 90033",
    phone: "(323) 268-5000",
    region: "Central",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: true,
    hasPerinatal: true,
    hasNICU: true,
    isSRC: true,
    isECPR: false,
    isPSC: true,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: [],
  },
  {
    id: "CHH",
    name: "Children's Hospital Los Angeles",
    shortName: "CHLA",
    address: "4650 Sunset Boulevard, Los Angeles, CA 90027",
    phone: "(323) 660-2450",
    region: "Central",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: "I",
    hasPTC: true,
    hasPMC: true,
    hasEDAP: true,
    hasPerinatal: false,
    hasNICU: true,
    isSRC: false,
    isECPR: false,
    isPSC: false,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: true,
    specialServices: [],
  },
  {
    id: "CHP",
    name: "Community Hospital of Huntington Park",
    shortName: "Huntington Park Community",
    address: "2623 E. Slauson Ave., Huntington Park, CA 90023",
    phone: "(323) 583-1931",
    region: "Central",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: false,
    hasPerinatal: false,
    hasNICU: false,
    isSRC: false,
    isECPR: false,
    isPSC: false,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: [],
  },
  {
    id: "CAL",
    name: "Dignity Health-California Hospital Medical Center",
    shortName: "California Hospital",
    address: "1401 South Grand Avenue, Los Angeles, CA 90015",
    phone: "(213) 748-2411",
    region: "Central",
    isBaseHospital: true,
    traumaLevel: "II",
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: true,
    hasPerinatal: true,
    hasNICU: true,
    isSRC: false,
    isECPR: false,
    isPSC: true,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: true,
    specialServices: [],
  },
  {
    id: "ELA",
    name: "East Los Angeles Doctors Hospital",
    shortName: "East LA Doctors",
    address: "4060 East Whittier Boulevard, Los Angeles, CA 90023",
    phone: "(323) 268-5514",
    region: "Central",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: true,
    hasPerinatal: false,
    hasNICU: false,
    isSRC: false,
    isECPR: false,
    isPSC: false,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: [],
  },
  {
    id: "QOA",
    name: "Hollywood Presbyterian Medical Center",
    shortName: "Hollywood Presbyterian",
    address: "1300 North Vermont Avenue, Los Angeles, CA 90027",
    phone: "(323) 413-3000",
    region: "Central",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: false,
    hasPerinatal: true,
    hasNICU: true,
    isSRC: true,
    isECPR: false,
    isPSC: true,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: true,
    specialServices: [],
  },
  {
    id: "KFL",
    name: "Kaiser Foundation Hospital - Los Angeles",
    shortName: "Kaiser Los Angeles",
    address: "4867 Sunset Boulevard, Los Angeles, CA 90027",
    phone: "(323) 783-4011",
    region: "Central",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: false,
    hasPerinatal: true,
    hasNICU: true,
    isSRC: false,
    isECPR: false,
    isPSC: true,
    isCSC: true,
    cscLevel: "I",
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: [],
  },
  {
    id: "LMC",
    name: "Los Angeles General Medical Center",
    shortName: "LA General (LAC+USC)",
    address: "1200 North State Street, Los Angeles, CA 90033",
    phone: "(323) 409-2800",
    region: "Central",
    isBaseHospital: true,
    traumaLevel: "I",
    pediatricTraumaLevel: "II",
    hasPTC: true,
    hasPMC: true,
    hasEDAP: true,
    hasPerinatal: true,
    hasNICU: true,
    isSRC: true,
    isECPR: false,
    isPSC: true,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: true,
    hasHelipad: true,
    specialServices: ["Hyperbaric Chamber - Catalina Isthmus", "SART Center"],
  },
  {
    id: "MLK",
    name: "Martin Luther King, Jr. Community Hospital",
    shortName: "MLK Community",
    address: "1680 East 120th Street, Los Angeles, CA 90059",
    phone: "(424) 388-8000",
    region: "Central",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: false,
    hasPerinatal: true,
    hasNICU: false,
    isSRC: false,
    isECPR: false,
    isPSC: false,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: [],
  },
  {
    id: "DCH",
    name: "PIH Health Downey Hospital",
    shortName: "PIH Downey",
    address: "11500 Brookshire Avenue, Downey, CA 90241",
    phone: "(562) 904-5000",
    region: "Central",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: true,
    hasPerinatal: false,
    hasNICU: false,
    isSRC: false,
    isECPR: false,
    isPSC: false,
    isCSC: true,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: [],
  },
  {
    id: "GSH",
    name: "PIH Health Good Samaritan Hospital",
    shortName: "Good Samaritan",
    address: "1225 Wilshire Blvd., Los Angeles, CA 90017",
    phone: "(213) 977-2121",
    region: "Central",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: false,
    hasPerinatal: true,
    hasNICU: true,
    isSRC: true,
    isECPR: false,
    isPSC: true,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: true,
    specialServices: [],
  },
];
