/**
 * LA County EMS Hospital Directory - East Region
 *
 * Hospitals in the East geographic region of LA County.
 * Used for MCI assignments and destination routing.
 *
 * Reference: LA County EMS Agency Ref 501 - Hospital Directory
 */

import type { Facility } from "../types";

/**
 * East region hospitals.
 */
export const EAST_HOSPITALS: Facility[] = [
  {
    id: "BEV",
    name: "Adventist Health White Memorial Montebello",
    shortName: "Adventist Montebello",
    address: "309 W. Beverly Boulevard, Montebello, CA 90640",
    phone: "(323) 725-5035",
    region: "East",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: false,
    hasPerinatal: false,
    hasNICU: false,
    isSRC: false,
    isECPR: false,
    isPSC: false,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: [],
  },
  {
    id: "ACH",
    name: "Alhambra Hospital Medical Center",
    shortName: "Alhambra",
    address: "100 South Raymond Avenue, Alhambra, CA 91801",
    phone: "(626) 570-1606",
    region: "East",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: false,
    hasPerinatal: false,
    hasNICU: false,
    isSRC: false,
    isECPR: false,
    isPSC: false,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: [],
  },
  {
    id: "FPH",
    name: "Emanate Health Foothill Presbyterian Hospital",
    shortName: "Foothill Presbyterian",
    address: "250 South Grand Avenue, Glendora, CA 91749",
    phone: "(626) 963-8411",
    region: "East",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: false,
    hasPerinatal: false,
    hasNICU: false,
    isSRC: false,
    isECPR: false,
    isPSC: false,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: true,
    specialServices: [],
  },
  {
    id: "ICH",
    name: "Emanate Health Inter-Community Hospital",
    shortName: "Inter-Community",
    address: "210 West San Bernardino Road, Covina, CA 91723",
    phone: "(626) 331-7331",
    region: "East",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: false,
    hasPerinatal: false,
    hasNICU: false,
    isSRC: true,
    isECPR: false,
    isPSC: false,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: [],
  },
  {
    id: "QVH",
    name: "Emanate Health Queen of the Valley Hospital",
    shortName: "Queen of the Valley",
    address: "1115 South Sunset Avenue, West Covina, CA 91790",
    phone: "(626) 962-4011",
    region: "East",
    isBaseHospital: true,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: true,
    hasPerinatal: true,
    hasNICU: true,
    isSRC: false,
    isECPR: false,
    isPSC: true,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: [],
  },
  {
    id: "GAR",
    name: "Garfield Medical Center",
    shortName: "Garfield",
    address: "525 North Garfield Avenue, Monterey Park, CA 91754",
    phone: "(626) 573-2222",
    region: "East",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: false,
    hasPerinatal: true,
    hasNICU: true,
    isSRC: true,
    isECPR: false,
    isPSC: true,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: [],
  },
  {
    id: "GEM",
    name: "Greater El Monte Community Hospital",
    shortName: "Greater El Monte",
    address: "1701 Santa Anita Avenue, South El Monte, CA 91733",
    phone: "(626) 579-7777",
    region: "East",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: false,
    hasPerinatal: false,
    hasNICU: false,
    isSRC: false,
    isECPR: false,
    isPSC: false,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: [],
  },
  {
    id: "HMH",
    name: "Huntington Hospital",
    shortName: "Huntington",
    address: "100 West California Boulevard, Pasadena, CA 91105",
    phone: "(626) 397-5000",
    region: "East",
    isBaseHospital: true,
    traumaLevel: "II",
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: true,
    hasPerinatal: true,
    hasNICU: true,
    isSRC: true,
    isECPR: false,
    isPSC: true,
    isCSC: true,
    cscLevel: "I",
    isBurnCenter: false,
    hasHelipad: true,
    specialServices: [],
  },
  {
    id: "KFA",
    name: "Kaiser Foundation Hospital - Baldwin Park",
    shortName: "Kaiser Baldwin Park",
    address: "1011 Baldwin Park Boulevard, Baldwin Park, CA 91706",
    phone: "(626) 851-1011",
    region: "East",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: false,
    hasPerinatal: true,
    hasNICU: true,
    isSRC: false,
    isECPR: false,
    isPSC: true,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: [],
  },
  {
    id: "KFB",
    name: "Kaiser Foundation Hospital - Downey",
    shortName: "Kaiser Downey",
    address: "9333 Imperial Highway, Downey, CA 90242",
    phone: "(562) 920-3023",
    region: "East",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: false,
    hasPerinatal: true,
    hasNICU: true,
    isSRC: false,
    isECPR: false,
    isPSC: true,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: [],
  },
  {
    id: "MPH",
    name: "Monterey Park Hospital",
    shortName: "Monterey Park",
    address: "900 South Atlantic Boulevard, Monterey Park, CA 91754",
    phone: "(626) 570-9000",
    region: "East",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: false,
    hasPerinatal: false,
    hasNICU: false,
    isSRC: false,
    isECPR: false,
    isPSC: false,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: [],
  },
  {
    id: "PIH",
    name: "PIH Health Whittier Hospital",
    shortName: "PIH Whittier",
    address: "12401 East Washington Boulevard, Whittier, CA 90602",
    phone: "(562) 698-0811",
    region: "East",
    isBaseHospital: true,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: true,
    hasPerinatal: true,
    hasNICU: true,
    isSRC: true,
    isECPR: false,
    isPSC: true,
    isCSC: true,
    cscLevel: "I",
    isBurnCenter: false,
    hasHelipad: true,
    specialServices: ["SART Center"],
  },
  {
    id: "PVC",
    name: "Pomona Valley Hospital Medical Center",
    shortName: "Pomona Valley",
    address: "1798 North Garey Avenue, Pomona, CA 91767",
    phone: "(909) 623-8715",
    region: "East",
    isBaseHospital: true,
    traumaLevel: "II",
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: true,
    hasPerinatal: true,
    hasNICU: true,
    isSRC: true,
    isECPR: false,
    isPSC: true,
    isCSC: true,
    cscLevel: "I",
    isBurnCenter: false,
    hasHelipad: true,
    specialServices: ["SART Center"],
  },
  {
    id: "SDC",
    name: "San Dimas Community Hospital",
    shortName: "San Dimas Community",
    address: "1350 West Covina Boulevard, San Dimas, CA 91773",
    phone: "(909) 599-6811",
    region: "East",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: false,
    hasPerinatal: false,
    hasNICU: false,
    isSRC: false,
    isECPR: false,
    isPSC: true,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: [],
  },
  {
    id: "SGC",
    name: "San Gabriel Valley Medical Center",
    shortName: "San Gabriel Valley",
    address: "438 West La Tunas Drive, San Gabriel, CA 91776",
    phone: "(626) 289-5454",
    region: "East",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: false,
    hasPerinatal: false,
    hasNICU: false,
    isSRC: false,
    isECPR: false,
    isPSC: false,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: ["SART Center - Adult EMS patients only"],
  },
  {
    id: "AMH",
    name: "USC Arcadia Hospital",
    shortName: "USC Arcadia",
    address: "300 West Huntington Drive, Arcadia, CA 91007",
    phone: "(626) 898-8000",
    region: "East",
    isBaseHospital: true,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: true,
    hasPerinatal: true,
    hasNICU: true,
    isSRC: true,
    isECPR: false,
    isPSC: true,
    isCSC: true,
    cscLevel: "I",
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: [],
  },
  {
    id: "WHH",
    name: "Whittier Hospital Medical Center",
    shortName: "Whittier Hospital",
    address: "9080 Colima Road, Whittier, CA 90605",
    phone: "(562) 945-3561",
    region: "East",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: false,
    hasPerinatal: true,
    hasNICU: false,
    isSRC: false,
    isECPR: false,
    isPSC: false,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: [],
  },
];
