/**
 * LA County EMS Hospital Directory - Out of County
 *
 * Hospitals outside LA County that are designated to receive
 * LA County 9-1-1 patients in certain circumstances.
 *
 * Reference: LA County EMS Agency Ref 501 - Hospital Directory (Page 8)
 */

import type { Facility } from "../types";

/**
 * Out of county hospitals that accept LA County 9-1-1 patients.
 */
export const OUT_OF_COUNTY_HOSPITALS: Facility[] = [
  {
    id: "LPI",
    name: "La Palma Intercommunity Hospital",
    shortName: "La Palma (Orange Co.)",
    address: "7901 Walker Street, La Palma, CA 90623",
    phone: "(714) 670-7400",
    region: "OutOfCounty",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: true,
    hasPerinatal: false,
    hasNICU: false,
    isSRC: false,
    isECPR: false,
    isPSC: false,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: [],
  },
  {
    id: "LRR",
    name: "Los Robles Regional Medical Center",
    shortName: "Los Robles (Ventura Co.)",
    address: "215 West Janss Road, Thousand Oaks, CA 91360",
    phone: "(805) 497-2727",
    region: "OutOfCounty",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: true,
    hasPerinatal: true,
    hasNICU: true,
    isSRC: true,
    isECPR: false,
    isPSC: true,
    isCSC: true,
    cscLevel: "I",
    isBurnCenter: false,
    hasHelipad: true,
    specialServices: [],
  },
  {
    id: "SJD",
    name: "St. Jude Medical Center",
    shortName: "St. Jude (Orange Co.)",
    address: "101 East Valencia Mesa Drive, Fullerton, CA 92635",
    phone: "(714) 871-3280",
    region: "OutOfCounty",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: false,
    hasPerinatal: true,
    hasNICU: true,
    isSRC: true,
    isECPR: false,
    isPSC: true,
    isCSC: true,
    cscLevel: "I",
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: [],
  },
  {
    id: "LAG",
    name: "UCI Health - Los Alamitos",
    shortName: "UCI Los Alamitos (Orange Co.)",
    address: "3751 Katella Avenue, Los Alamitos, CA 90720",
    phone: "(562) 598-1311",
    region: "OutOfCounty",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: false,
    hasPerinatal: false,
    hasNICU: false,
    isSRC: true,
    isECPR: false,
    isPSC: true,
    isCSC: true,
    cscLevel: "I",
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: [],
  },
  {
    id: "UCI",
    name: "UC Irvine Medical Center",
    shortName: "UC Irvine (Orange Co.)",
    address: "101 The City Drive, R007E62, Orange, CA 92868",
    phone: "(714) 456-6011",
    region: "OutOfCounty",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: false,
    hasPerinatal: true,
    hasNICU: true,
    isSRC: false,
    isECPR: false,
    isPSC: false,
    isCSC: true,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: true,
    specialServices: [],
  },
];
