/**
 * LA County EMS Hospital Directory - West Region
 *
 * Hospitals in the West geographic region of LA County.
 * Used for MCI assignments and destination routing.
 *
 * Reference: LA County EMS Agency Ref 501 - Hospital Directory
 */

import type { Facility } from "../types";

/**
 * West region hospitals.
 */
export const WEST_HOSPITALS: Facility[] = [
  {
    id: "CSM",
    name: "Cedars Sinai Medical Center",
    shortName: "Cedars Sinai",
    address: "8700 Beverly Boulevard, Los Angeles, CA 90048",
    phone: "(310) 855-5000",
    region: "West",
    isBaseHospital: true,
    traumaLevel: "I",
    pediatricTraumaLevel: "II",
    hasPTC: true,
    hasPMC: true,
    hasEDAP: true,
    hasPerinatal: true,
    hasNICU: true,
    isSRC: true,
    isECPR: true,
    isPSC: false,
    isCSC: true,
    cscLevel: "I",
    isBurnCenter: false,
    hasHelipad: true,
    specialServices: [],
  },
  {
    id: "DFM",
    name: "Cedars Sinai Marina Del Rey Hospital",
    shortName: "Cedars Marina Del Rey",
    address: "4650 Lincoln Boulevard, Marina Del Rey, CA 90291",
    phone: "(310) 823-8911",
    region: "West",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: false,
    hasPerinatal: false,
    hasNICU: false,
    isSRC: false,
    isECPR: false,
    isPSC: false,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: true,
    specialServices: [],
  },
  {
    id: "KFW",
    name: "Kaiser Foundation Hospital - West Los Angeles",
    shortName: "Kaiser West LA",
    address: "6041 Cadillac Avenue, Los Angeles, CA 90034",
    phone: "(323) 857-2000",
    region: "West",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: false,
    hasPerinatal: true,
    hasNICU: true,
    isSRC: false,
    isECPR: false,
    isPSC: true,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: [],
  },
  {
    id: "SJH",
    name: "Providence Saint John's Health Center",
    shortName: "Saint John's",
    address: "2121 Santa Monica Blvd., Santa Monica, CA 90404",
    phone: "(310) 829-5511",
    region: "West",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: false,
    hasPerinatal: true,
    hasNICU: true,
    isSRC: true,
    isECPR: false,
    isPSC: true,
    isCSC: true,
    cscLevel: "I",
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: [],
  },
  {
    id: "UCL",
    name: "Ronald Reagan UCLA Medical Center",
    shortName: "UCLA Medical Center",
    address: "757 Westwood Plaza, Los Angeles, CA 90095",
    phone: "(310) 825-9111",
    region: "West",
    isBaseHospital: true,
    traumaLevel: "I",
    pediatricTraumaLevel: "II",
    hasPTC: true,
    hasPMC: true,
    hasEDAP: true,
    hasPerinatal: true,
    hasNICU: true,
    isSRC: true,
    isECPR: true,
    isPSC: false,
    isCSC: true,
    cscLevel: "I",
    isBurnCenter: false,
    hasHelipad: true,
    specialServices: [],
  },
  {
    id: "SMH",
    name: "Santa Monica-UCLA Medical Center",
    shortName: "Santa Monica-UCLA",
    address: "1250 16th Street, Santa Monica, CA 90404",
    phone: "(310) 319-4000",
    region: "West",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: true,
    hasPerinatal: true,
    hasNICU: true,
    isSRC: true,
    isECPR: false,
    isPSC: true,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: ["SART Center"],
  },
  {
    id: "BMC",
    name: "Southern California Hospital at Culver City",
    shortName: "SoCal Culver City",
    address: "3828 Delmas Terrace, Culver City, CA 90231",
    phone: "(310) 836-7000",
    region: "West",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: false,
    hasPerinatal: false,
    hasNICU: false,
    isSRC: false,
    isECPR: false,
    isPSC: false,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: [],
  },
];
