/**
 * LA County EMS Hospital Directory - South Region
 *
 * Hospitals in the South geographic region of LA County.
 * Used for MCI assignments and destination routing.
 *
 * Reference: LA County EMS Agency Ref 501 - Hospital Directory
 */

import type { Facility } from "../types";

/**
 * South region hospitals.
 */
export const SOUTH_HOSPITALS: Facility[] = [
  {
    id: "AHM",
    name: "Catalina Island Medical Center",
    shortName: "Catalina Island",
    address: "100 Falls Canyon Road, Avalon, CA 90704",
    phone: "(310) 510-0700",
    region: "South",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: false,
    hasPerinatal: false,
    hasNICU: false,
    isSRC: false,
    isECPR: false,
    isPSC: false,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: [],
  },
  {
    id: "CNT",
    name: "Centinela Hospital Medical Center",
    shortName: "Centinela",
    address: "555 East Hardy Street, Inglewood, CA 90301",
    phone: "(310) 673-4660",
    region: "South",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: true,
    hasPerinatal: false,
    hasNICU: false,
    isSRC: true,
    isECPR: false,
    isPSC: true,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: [],
  },
  {
    id: "CPM",
    name: "Coast Plaza Hospital",
    shortName: "Coast Plaza",
    address: "13100 Studebaker Road, Norwalk, CA 90650",
    phone: "(562) 868-3751",
    region: "South",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: false,
    hasPerinatal: false,
    hasNICU: false,
    isSRC: false,
    isECPR: false,
    isPSC: false,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: [],
  },
  {
    id: "PLB",
    name: "College Medical Center",
    shortName: "College Medical",
    address: "2776 Pacific Avenue, Long Beach, CA 90806",
    phone: "(562) 595-1911",
    region: "South",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: false,
    hasPerinatal: false,
    hasNICU: false,
    isSRC: false,
    isECPR: false,
    isPSC: false,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: [],
  },
  {
    id: "SMM",
    name: "Dignity Health-St. Mary Medical Center",
    shortName: "St. Mary Long Beach",
    address: "1050 Linden Avenue, Long Beach, CA 90813",
    phone: "(562) 491-9000",
    region: "South",
    isBaseHospital: true,
    traumaLevel: "II",
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: true,
    hasPerinatal: true,
    hasNICU: true,
    isSRC: true,
    isECPR: false,
    isPSC: true,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: true,
    specialServices: [],
  },
  {
    id: "HGH",
    name: "Harbor-UCLA Medical Center",
    shortName: "Harbor-UCLA",
    address: "1000 West Carson Street, Torrance, CA 90502",
    phone: "(424) 306-4000",
    region: "South",
    isBaseHospital: true,
    traumaLevel: "I",
    pediatricTraumaLevel: "II",
    hasPTC: true,
    hasPMC: true,
    hasEDAP: true,
    hasPerinatal: true,
    hasNICU: true,
    isSRC: true,
    isECPR: false,
    isPSC: false,
    isCSC: true,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: true,
    specialServices: ["SART Center - DCFS only"],
  },
  {
    id: "KFH",
    name: "Kaiser Foundation Hospital - South Bay",
    shortName: "Kaiser South Bay",
    address: "25825 South Vermont Avenue, Harbor City, CA 90710",
    phone: "(310) 325-5111",
    region: "South",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: false,
    hasPerinatal: true,
    hasNICU: true,
    isSRC: false,
    isECPR: false,
    isPSC: true,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: [],
  },
  {
    id: "MHG",
    name: "Memorial Hospital of Gardena",
    shortName: "Memorial Gardena",
    address: "1145 West Redondo Beach Boulevard, Gardena, CA 90247",
    phone: "(310) 532-4200",
    region: "South",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: false,
    hasPerinatal: false,
    hasNICU: false,
    isSRC: false,
    isECPR: false,
    isPSC: true,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: [],
  },
  {
    id: "LBM",
    name: "MemorialCare Long Beach Medical Center",
    shortName: "Long Beach Memorial",
    address: "2801 Atlantic Avenue, Long Beach, CA 90806",
    phone: "(562) 933-2000",
    region: "South",
    isBaseHospital: true,
    traumaLevel: "II",
    pediatricTraumaLevel: "II",
    hasPTC: true,
    hasPMC: true,
    hasEDAP: true,
    hasPerinatal: true,
    hasNICU: true,
    isSRC: true,
    isECPR: false,
    isPSC: false,
    isCSC: true,
    cscLevel: "I",
    isBurnCenter: false,
    hasHelipad: true,
    specialServices: ["SART Center - Law Enforcement ONLY"],
  },
  {
    id: "NOR",
    name: "Norwalk Community Hospital",
    shortName: "Norwalk Community",
    address: "13222 Bloomfield Avenue, Norwalk, CA 90650",
    phone: "(562) 863-4763",
    region: "South",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: false,
    hasPerinatal: false,
    hasNICU: false,
    isSRC: false,
    isECPR: false,
    isPSC: false,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: [],
  },
  {
    id: "SPP",
    name: "Providence Little Company of Mary Medical Center - San Pedro",
    shortName: "Little Company San Pedro",
    address: "1300 West Seventh Street, San Pedro, CA 90732",
    phone: "(310) 832-3311",
    region: "South",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: true,
    hasPerinatal: false,
    hasNICU: false,
    isSRC: false,
    isECPR: false,
    isPSC: true,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: ["SART Center"],
  },
  {
    id: "LCM",
    name: "Providence Little Company of Mary Medical Center - Torrance",
    shortName: "Little Company Torrance",
    address: "4101 Torrance Boulevard, Torrance, CA 90503",
    phone: "(310) 540-7676",
    region: "South",
    isBaseHospital: true,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: true,
    hasPerinatal: true,
    hasNICU: true,
    isSRC: true,
    isECPR: false,
    isPSC: true,
    isCSC: true,
    cscLevel: "I",
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: [],
  },
  {
    id: "SFM",
    name: "St. Francis Medical Center",
    shortName: "St. Francis",
    address: "3630 East Imperial Highway, Lynwood, CA 90262",
    phone: "(310) 900-8900",
    region: "South",
    isBaseHospital: true,
    traumaLevel: "II",
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: true,
    hasPerinatal: true,
    hasNICU: true,
    isSRC: true,
    isECPR: false,
    isPSC: true,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: true,
    specialServices: [],
  },
  {
    id: "TOR",
    name: "Torrance Memorial Medical Center",
    shortName: "Torrance Memorial",
    address: "3330 West Lomita Boulevard, Torrance, CA 90505",
    phone: "(310) 325-9110",
    region: "South",
    isBaseHospital: true,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: true,
    hasPerinatal: true,
    hasNICU: true,
    isSRC: true,
    isECPR: true,
    isPSC: false,
    isCSC: true,
    cscLevel: "I",
    isBurnCenter: true,
    hasHelipad: false,
    specialServices: [],
  },
  {
    id: "DHL",
    name: "UCI Health - Lakewood",
    shortName: "UCI Lakewood",
    address: "3700 S. Street, Lakewood, CA 90712",
    phone: "(562) 531-2550",
    region: "South",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: false,
    hasPerinatal: false,
    hasNICU: false,
    isSRC: true,
    isECPR: false,
    isPSC: true,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: [],
  },
];
