/**
 * LA County EMS Hospital Directory - North Region
 *
 * Hospitals in the North geographic region of LA County.
 * Used for MCI assignments and destination routing.
 *
 * Reference: LA County EMS Agency Ref 501 - Hospital Directory
 */

import type { Facility } from "../types";

/**
 * North region hospitals.
 */
export const NORTH_HOSPITALS: Facility[] = [
  {
    id: "GWT",
    name: "Adventist Health Glendale",
    shortName: "Adventist Glendale",
    address: "1509 East Wilson Terrace, Glendale, CA 91206",
    phone: "(818) 409-8000",
    region: "North",
    isBaseHospital: true,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: true,
    hasPerinatal: true,
    hasNICU: true,
    isSRC: true,
    isECPR: false,
    isPSC: true,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: true,
    specialServices: [],
  },
  {
    id: "AVH",
    name: "Antelope Valley Medical Center",
    shortName: "Antelope Valley",
    address: "1600 West Avenue J, Lancaster, CA 93534",
    phone: "(661) 949-5000",
    region: "North",
    isBaseHospital: true,
    traumaLevel: "II",
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: true,
    hasPerinatal: true,
    hasNICU: true,
    isSRC: true,
    isECPR: false,
    isPSC: true,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: true,
    specialServices: ["SART Center"],
  },
  {
    id: "GMH",
    name: "Dignity Health-Glendale Memorial Hospital and Health Center",
    shortName: "Glendale Memorial",
    address: "1420 South Central Avenue, Glendale, CA 91204",
    phone: "(818) 502-1900",
    region: "North",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: true,
    hasPerinatal: true,
    hasNICU: true,
    isSRC: true,
    isECPR: false,
    isPSC: true,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: [],
  },
  {
    id: "NRH",
    name: "Dignity Health-Northridge Hospital Medical Center",
    shortName: "Northridge Hospital",
    address: "18300 Roscoe Boulevard, Northridge, CA 91328",
    phone: "(818) 885-8500",
    region: "North",
    isBaseHospital: true,
    traumaLevel: "II",
    pediatricTraumaLevel: "II",
    hasPTC: true,
    hasPMC: true,
    hasEDAP: true,
    hasPerinatal: true,
    hasNICU: true,
    isSRC: true,
    isECPR: false,
    isPSC: false,
    isCSC: true,
    cscLevel: "II",
    isBurnCenter: false,
    hasHelipad: true,
    specialServices: ["SART Center - Law Enforcement ONLY"],
  },
  {
    id: "ENH",
    name: "Encino Hospital Medical Center",
    shortName: "Encino Hospital",
    address: "16237 Ventura Boulevard, Encino, CA 91436",
    phone: "(818) 995-5000",
    region: "North",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: true,
    hasPerinatal: false,
    hasNICU: false,
    isSRC: false,
    isECPR: false,
    isPSC: true,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: [],
  },
  {
    id: "HMN",
    name: "Henry Mayo Newhall Hospital",
    shortName: "Henry Mayo",
    address: "23845 West McBean Parkway, Valencia, CA 91355",
    phone: "(661) 253-8000",
    region: "North",
    isBaseHospital: true,
    traumaLevel: "II",
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: true,
    hasPerinatal: true,
    hasNICU: true,
    isSRC: true,
    isECPR: false,
    isPSC: true,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: true,
    specialServices: [],
  },
  {
    id: "KFP",
    name: "Kaiser Foundation Hospital - Panorama City",
    shortName: "Kaiser Panorama City",
    address: "13652 Cantara Street, Panorama City, CA 91402",
    phone: "(818) 375-2000",
    region: "North",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: false,
    hasPerinatal: true,
    hasNICU: true,
    isSRC: false,
    isECPR: false,
    isPSC: true,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: [],
  },
  {
    id: "KFO",
    name: "Kaiser Foundation Hospital - Woodland Hills",
    shortName: "Kaiser Woodland Hills",
    address: "5601 De Soto Avenue, Woodland Hills, CA 91367",
    phone: "(818) 719-2000",
    region: "North",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: false,
    hasPerinatal: true,
    hasNICU: true,
    isSRC: false,
    isECPR: false,
    isPSC: true,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: [],
  },
  {
    id: "MCP",
    name: "Mission Community Hospital",
    shortName: "Mission Community",
    address: "14850 Roscoe Boulevard, Panorama City, CA 91402",
    phone: "(818) 787-2222",
    region: "North",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: false,
    hasPerinatal: false,
    hasNICU: false,
    isSRC: false,
    isECPR: false,
    isPSC: true,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: [],
  },
  {
    id: "OVM",
    name: "Olive View Medical Center",
    shortName: "Olive View-UCLA",
    address: "14445 Olive View Drive, Sylmar, CA 91342",
    phone: "(747) 210-3000",
    region: "North",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: true,
    hasPerinatal: true,
    hasNICU: true,
    isSRC: false,
    isECPR: false,
    isPSC: false,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: true,
    specialServices: ["SART Center - DCFS only"],
  },
  {
    id: "PAC",
    name: "Pacifica Hospital of the Valley",
    shortName: "Pacifica Valley",
    address: "9449 San Fernando Road, Sun Valley, CA 91352",
    phone: "(818) 767-3310",
    region: "North",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: false,
    hasPerinatal: false,
    hasNICU: false,
    isSRC: false,
    isECPR: false,
    isPSC: false,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: [],
  },
  {
    id: "LCH",
    name: "Palmdale Regional Medical Center",
    shortName: "Palmdale Regional",
    address: "38600 Medical Center Drive, Palmdale, CA 93551",
    phone: "(661) 382-5000",
    region: "North",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: false,
    hasPerinatal: false,
    hasNICU: false,
    isSRC: true,
    isECPR: false,
    isPSC: true,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: [],
  },
  {
    id: "TRM",
    name: "Providence Cedars-Sinai Tarzana Medical Center",
    shortName: "Tarzana Medical Center",
    address: "18321 Clark Street, Tarzana, CA 91356",
    phone: "(818) 881-0800",
    region: "North",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: true,
    hasPerinatal: true,
    hasNICU: true,
    isSRC: true,
    isECPR: false,
    isPSC: true,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: [],
  },
  {
    id: "HCH",
    name: "Providence Holy Cross Medical Center",
    shortName: "Holy Cross",
    address: "15031 Rinaldi Street, Mission Hills, CA 91345",
    phone: "(818) 365-8051",
    region: "North",
    isBaseHospital: true,
    traumaLevel: "II",
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: true,
    hasPerinatal: true,
    hasNICU: true,
    isSRC: true,
    isECPR: false,
    isPSC: true,
    isCSC: true,
    cscLevel: "I",
    isBurnCenter: false,
    hasHelipad: true,
    specialServices: [],
  },
  {
    id: "SJS",
    name: "Providence Saint Joseph Medical Center",
    shortName: "Saint Joseph Burbank",
    address: "501 South Buena Vista Street, Burbank, CA 91505",
    phone: "(818) 843-5111",
    region: "North",
    isBaseHospital: true,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: true,
    hasPerinatal: true,
    hasNICU: true,
    isSRC: true,
    isECPR: false,
    isPSC: true,
    isCSC: true,
    cscLevel: "I",
    isBurnCenter: false,
    hasHelipad: true,
    specialServices: [],
  },
  {
    id: "SOC",
    name: "Sherman Oaks Hospital",
    shortName: "Sherman Oaks",
    address: "4929 Van Nuys Boulevard, Sherman Oaks, CA 91403",
    phone: "(818) 981-7111",
    region: "North",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: true,
    hasPerinatal: false,
    hasNICU: false,
    isSRC: false,
    isECPR: false,
    isPSC: true,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: true,
    specialServices: [],
  },
  {
    id: "HWH",
    name: "UCLA West Valley Medical Center",
    shortName: "UCLA West Valley",
    address: "7300 Medical Center Drive, West Hills, CA 91307",
    phone: "(818) 676-4000",
    region: "North",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: true,
    hasPerinatal: false,
    hasNICU: false,
    isSRC: true,
    isECPR: false,
    isPSC: true,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: true,
    specialServices: [],
  },
  {
    id: "VHH",
    name: "USC Verdugo Hills Hospital",
    shortName: "USC Verdugo Hills",
    address: "1812 Verdugo Boulevard, Glendale, CA 91208",
    phone: "(818) 790-7100",
    region: "North",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: false,
    hasEDAP: true,
    hasPerinatal: false,
    hasNICU: false,
    isSRC: false,
    isECPR: false,
    isPSC: true,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: true,
    specialServices: [],
  },
  {
    id: "VPH",
    name: "Valley Presbyterian Hospital",
    shortName: "Valley Presbyterian",
    address: "15107 Van Owen Street, Van Nuys, CA 91405",
    phone: "(818) 782-6600",
    region: "North",
    isBaseHospital: false,
    traumaLevel: null,
    pediatricTraumaLevel: null,
    hasPTC: false,
    hasPMC: true,
    hasEDAP: true,
    hasPerinatal: true,
    hasNICU: true,
    isSRC: true,
    isECPR: false,
    isPSC: true,
    isCSC: false,
    cscLevel: null,
    isBurnCenter: false,
    hasHelipad: false,
    specialServices: [],
  },
];
