/**
 * LA County Protocol Whitelist
 *
 * Source: LA County Department of Health Services EMS Agency
 * Last Updated: 2025-12-19
 *
 * Total protocols: 291
 */

export type ProviderScope = "EMT" | "Paramedic" | "both";

export type ProtocolCategory =
  | "treatment_protocol"
  | "mcg"
  | "drug_reference"
  | "policy"
  | "administrative"
  | "other";

export interface LACountyProtocol {
  name: string;
  category: ProtocolCategory;
  scope: ProviderScope;
  isPediatric: boolean;
  revisionDate?: string;
}

/**
 * Authoritative whitelist of all LA County EMS protocols.
 * Every protocol citation in LLM responses MUST be validated against this list.
 */
export const LA_COUNTY_PROTOCOLS: Record<string, LACountyProtocol> = {
  "200": {
    name: "Table of Contents",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: undefined,
  },
  "201": {
    name: "Medical Management of Prehospital Care",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-25",
  },
  "202": {
    name: "Policy Development",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "202.1": {
    name: "Committee Assignment",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "202.2": {
    name: "Summaryof Comments",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "204": {
    name: "Medical Council",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: undefined,
  },
  "205": {
    name: "ITACommittee",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "10-01-24",
  },
  "206": {
    name: "Emergency Medical Services Commission",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "10-01-24",
  },
  "207": {
    name: "EMSCCommittees",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "210": {
    name: "EMSAgency Org Chart",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: undefined,
  },
  "212": {
    name: "County Administrative Staff Emergency Medical Services",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "01-01-25",
  },
  "214": {
    name: "Base Hospital and Provider Agency Reporting Responsibilities",
    category: "policy",
    scope: "both",
    isPediatric: false,
    revisionDate: "04-01-24",
  },
  "215": {
    name: "ELCo R",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: undefined,
  },
  "216-P": {
    name: "Ped AC",
    category: "policy",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "04-01-24",
  },
  "218": {
    name: "THAC",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-24",
  },
  "219": {
    name: "Allergy",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-23",
  },
  "222": {
    name: "Downgrade",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "226": {
    name: "Private Provider Agency Non 9-1-1 Medical Dispatch",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "10-01-21",
  },
  "226.112": {
    name: "Private Provider Agency Non-9-1-1 Medical Dispatch Caller Interview Guidelines",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "10-01-21",
  },
  "227": {
    name: "Dispatching of Emergency Medical Services",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "01-01-22",
  },
  "227.1": {
    name: "EMSDispatch Guidelines",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "01-01-2022",
  },
  "228": {
    name: "ReddiNet Utilization",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-24",
  },
  "238": {
    name: "671",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "10-01-24",
  },
  "246": {
    name: "111",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-22",
  },
  "302": {
    name: "9-1-1 Receiving Hospital Standards",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "10-01-24",
  },
  "318": {
    name: "PMCStandards",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "320": {
    name: "SRCStandards",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "320.1": {
    name: "Target Temperature",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "320.2": {
    name: "Sample STEMIMOU",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "320.3": {
    name: "SRCPerformance Measures",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "321": {
    name: "ECPRReceiving Center Standards",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: undefined,
  },
  "322": {
    name: "Stroke Standards",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-22",
  },
  "322.1": {
    name: "Stroke Performance Measures",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "10-01-23",
  },
  "324": {
    name: "SARTCenter Standards",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "326": {
    name: "Psych UCCStandards",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-23",
  },
  "328": {
    name: "Sobering Center Standards",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-23",
  },
  "401": {
    name: ".md",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "01-01-2025",
  },
  "401.1": {
    name: "Ambulance Operators",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-22-25",
  },
  "401.2": {
    name: "Licensed Ambulette Operators",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: undefined,
  },
  "412.2": {
    name: "AED Service Provider Annual Report",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "10-01-19",
  },
  "414.1": {
    name: "RCP RN HRCombo",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-22",
  },
  "416": {
    name: "Assessment Unit",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "01-01-23",
  },
  "416.1": {
    name: "Temporary Upgrade of an Assessment Unit to an ALS Unit",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-22",
  },
  "416.2": {
    name: "Downgrade of an ALS Unit from Temporarily Upgraded Assessment Unit",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-22",
  },
  "419": {
    name: "Prehospital EMSAircraft Operations",
    category: "policy",
    scope: "both",
    isPediatric: false,
    revisionDate: "04-01-22",
  },
  "420": {
    name: "Private Ambulance Operator Medical Director",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "422": {
    name: "Paramedic Provider Statusfor LE",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: undefined,
  },
  "424": {
    name: "Triageto Alternate Destination Program",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: undefined,
  },
  "450": {
    name: "Ambulance Ordinance",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-25",
  },
  "451.5": {
    name: "Noticeof Violation EOA",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: undefined,
  },
  "501": {
    name: "Hospital Directory",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "09-15-25",
  },
  "502": {
    name: "Patient Destination",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "503": {
    name: "Guidelinesfor Hospitals Requesting Diversionof ALSPatients",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-25",
  },
  "503.2": {
    name: "Diversion Request Quick Reference Guide",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-25",
  },
  "505": {
    name: "APOT",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "506": {
    name: "Trauma Triage Decision Scheme",
    category: "policy",
    scope: "both",
    isPediatric: false,
    revisionDate: "01-01-24", // Actual source date; 07-01-25 update pending from DHS
  },
  "506.2": {
    name: "a Trauma Centersand911Umbrella",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: undefined,
  },
  "506.29": {
    name: "1 1Trauma Re Triage",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "12-01-23",
  },
  "508.1": {
    name: "SARTRoster",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-10-25",
  },
  "510": {
    name: "Pediatric Patient Destination",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "01-01-23",
  },
  "512": {
    name: "Burn Patient Destination",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "01-01-24",
  },
  "513": {
    name: "ST-Elevation Myocardial Infarction (STEMI) Patient Destination",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-25",
  },
  "515": {
    name: "Air Ambulance Transport",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "10-01-24",
  },
  "516": {
    name: "Cardiac Arrest (Non-Traumatic) Patient Destination",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-25",
  },
  "517": {
    name: "Guidelines for Determining Interfacility Level of Transport",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "01-01-23",
  },
  "517-P": {
    name: "Private Provider Transport Guidelines",
    category: "policy",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "07-01-24",
  },
  "518": {
    name: "Decompression Emergencies Patient Destination",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-25",
  },
  "519": {
    name: "Managementof MCI",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "519.1": {
    name: "MCIDefinitions",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "519.2": {
    name: "MCITriage Guidelines",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "519.3": {
    name: "MCITransport Management",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "519.4": {
    name: "MCITransport Priority",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "519.5": {
    name: "MCIField Decontamination Guidelines",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "519.6": {
    name: "MCIMaps Bed Availability Worksheets",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "520": {
    name: "Catalina Island Medical Center (AHM) Transfer Process",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "01-01-22",
  },
  "526": {
    name: "Psych UCCPatient Destination",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-25",
  },
  "526.1": {
    name: "Psych UCCMedical Clearance Screening Tool",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-25",
  },
  "528": {
    name: "Intoxicated Patient Destination",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-23",
  },
  "528.1": {
    name: "Sobering Center Medical Clearance Screening Tool",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "01-01-24",
  },
  "600": {
    name: "Tableof Contents",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: undefined,
  },
  "606": {
    name: "Documentation of Prehospital Care",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-24",
  },
  "618": {
    name: "EMS Quality Improvement Program (EQIP) Committees",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "10-01-23",
  },
  "620": {
    name: "EMSQIProgram",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "621": {
    name: "Notification of Personnel Change Form - Provider Agency and Training Programs",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "01-01-23",
  },
  "621.2": {
    name: "Notification of Personnel Change Form - Hospital Programs",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "09-01-25",
  },
  "622": {
    name: "Release of EMS Data",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "01-01-25",
  },
  "622.1": {
    name: "Data Request and Levels of Support",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "01-01-2025",
  },
  "622.2": {
    name: "Limited Data Set Information",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "01-01-25",
  },
  "622.3": {
    name: "Intended Use of Limited Data Set Information",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "01-01-25",
  },
  "622.4": {
    name: "Data Use Agreement",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "01-01-25",
  },
  "622.5": {
    name: "Confidentiality Agreement",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "01-01-25",
  },
  "648": {
    name: "SRC Data Dictionary",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: undefined,
  },
  "701.1": {
    name: "Physician Confirmation of Agreement to Purchase Drugs and Medical Supplies",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-21",
  },
  "702": {
    name: "Controlled Drugs",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "702.1": {
    name: "Medical Director Contolled Drug",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "702.2": {
    name: "Daily Controlled Drug Inventory",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "702.3": {
    name: "Controlled Drug Loss",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "702.4": {
    name: "Monthly Drug Storage Form",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "703": {
    name: "ALS Unit Inventory",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "01-01-25",
  },
  "703.1": {
    name: "Private Provider Interfacility Transfer ALS Unit Inventory",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-23",
  },
  "704": {
    name: "Assessment Unit Inventory",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "12-01-23",
  },
  "706": {
    name: "ALS EMS Aircraft Inventory",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "12-01-23",
  },
  "712": {
    name: "Nurse Staffed Specialty Care Transport Unit Inventory",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-2023",
  },
  "719": {
    name: "Fireline Emergency Technician-Paramedic (FEMP) Inventory",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "12-01-23",
  },
  "800": {
    name: "Table of Contents",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: undefined,
  },
  "802": {
    name: "EMT Scope of Practice",
    category: "policy",
    scope: "EMT",
    isPediatric: false,
    revisionDate: "07-01-25",
  },
  "802.1": {
    name: "EMTField Reference",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: undefined,
  },
  "803": {
    name: "Paramedic Scopeof Practice",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-25",
  },
  "803.1": {
    name: "Paramedic Field Reference",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-25",
  },
  "807": {
    name: "Haz Mat Exposure",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "807.1": {
    name: "Hazmat Flowchart",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "815": {
    name: "Honoring Prehospital DNR/POLST/End of Life Option",
    category: "policy",
    scope: "both",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "815.1": {
    name: "EMS Prehospital DNR Form",
    category: "policy",
    scope: "both",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "815.2": {
    name: "POLST Form",
    category: "policy",
    scope: "both",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "815.3": {
    name: "End of Life Option Field Quick Reference Guide",
    category: "policy",
    scope: "both",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "817": {
    name: "Regional Mobile Response Team",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "822": {
    name: "Suspected Child Abuse Report",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: undefined,
  },
  "822.2": {
    name: "Suspected Child Abuse Report Form",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: undefined,
  },
  "822.17": {
    name: "Guide to Suspected Child Abuse Reporting",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "01-01-23",
  },
  "822.37": {
    name: "Employee Acknowledgment as a Mandated Reporter to Report Child Abuse/Neglect",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-22",
  },
  "823": {
    name: "Elder Abuse Guidelines",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "823.1": {
    name: "Report of Suspected Dependent Adult Elder Abuse Form",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "834": {
    name: "Patient Refusal of Treatment/Transport/Treat and Release",
    category: "policy",
    scope: "both",
    isPediatric: false,
    revisionDate: "07-01-25",
  },
  "834.1": {
    name: "AMAQuick Reference Guide",
    category: "policy",
    scope: "both",
    isPediatric: false,
    revisionDate: "07-01-25",
  },
  "836": {
    name: "Communicable Disease Exposure - Court Petition to Test Accused Blood",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-22",
  },
  "838": {
    name: "Application of Patient Restraints",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-25",
  },
  "842": {
    name: "Mass Gatherings Interface with Emergency Medical Services",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-22",
  },
  "1006": {
    name: "Paramedic Accreditation",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "1010": {
    name: "Mobile Intensive Care Nurse (MICN) Certification",
    category: "policy",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "10-01-24",
  },
  "1011": {
    name: "MICNField Observation",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "1012": {
    name: "16",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: undefined,
  },
  "1102.3": {
    name: "DRCEquipment Release Agreement",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: undefined,
  },
  "1106": {
    name: "2",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: undefined,
  },
  "1106.1": {
    name: "0",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-24",
  },
  "1106.3": {
    name: "LPCPhotograph",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-24",
  },
  "1107.16": {
    name: "1 14",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-23",
  },
  "1108": {
    name: "Chempack Deploymentfor Nerve Agent Release",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "1108.1": {
    name: "Chempack Inventory",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "1108.2": {
    name: "Chempack Photograph",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "1114": {
    name: "Hospital EMSSurge Assistance",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "01-01-24",
  },
  "1124": {
    name: "Disaster Exercise Drills",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "1130": {
    name: "Trauma Center Preparedness",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "1138": {
    name: "1",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-23",
  },
  "1138.2": {
    name: "Local Burn Specialist Call Panel",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "01-01-24",
  },
  "1142-P": {
    name: "Policy Waivers",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "04-01-24",
  },
  "1142.1": {
    name: "Prehospital Care Policy Waiver Request Form",
    category: "policy",
    scope: "both",
    isPediatric: false,
    revisionDate: "04-01-24",
  },
  "1143": {
    name: "Medical Oversight During COVID 19Outbreak",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "01-01-24",
  },
  "1200.0": {
    name: "Tableof Contents",
    category: "treatment_protocol",
    scope: "both",
    isPediatric: false,
    revisionDate: "07-01-25",
  },
  "1200.1": {
    name: "General Instructions",
    category: "treatment_protocol",
    scope: "both",
    isPediatric: false,
    revisionDate: "07-01-25",
  },
  "1200.2": {
    name: "Base Contact Requirements",
    category: "treatment_protocol",
    scope: "both",
    isPediatric: false,
    revisionDate: "07-01-25",
  },
  "1200.3": {
    name: "Provider Impression",
    category: "treatment_protocol",
    scope: "both",
    isPediatric: false,
    revisionDate: "07-01-25",
  },
  "1200.4": {
    name: "BLSUpgradeto ALSAssessment",
    category: "treatment_protocol",
    scope: "both",
    isPediatric: false,
    revisionDate: "07-01-25",
  },
  "1201": {
    name: "Assessment",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "10-01-23",
  },
  "1202": {
    name: "General Medical",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "1202-P": {
    name: "PGeneral Medical",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "07-01-20",
  },
  "1203": {
    name: "Diabetic Emergencies",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "1203-P": {
    name: "PDiabetic Emergencies",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "10-01-24",
  },
  "1204": {
    name: "Fever Sepsis",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "1204-P": {
    name: "PFever Sepsis",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "07-01-24",
  },
  "1205": {
    name: "GIGU",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "1205-P": {
    name: "PGI GUEmergencies",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "07-01-24",
  },
  "1206": {
    name: "Medical Device Malfunction",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "1206-P": {
    name: "PMedical Device Malfunction",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "07-01-24",
  },
  "1207": {
    name: "Shock Hypotension",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "1207-P": {
    name: "PShock Hypotension",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "10-01-24",
  },
  "1209": {
    name: "Behavioral Psychiatric Crisis",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-25",
  },
  "1209-P": {
    name: "PBehavioral Psych Crisis",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "07-01-25",
  },
  "1210": {
    name: "Cardiac Arrest",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-25",
  },
  "1210-P": {
    name: "PCardiac Arrest",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "04-01-25",
  },
  "1211": {
    name: "Cardiac Chest Pain",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "1212": {
    name: "Cardiac Dysrhythmia Bradycardia",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "1212-P": {
    name: "PCardiac Dysrhythmia Bradycardia",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "01-01-25",
  },
  "1213": {
    name: "Cardiac Dysrhythmia Tachycardia",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "1213-P": {
    name: "PCardiac Dysrhythmia Tachycardia",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "04-01-25",
  },
  "1214": {
    name: "Pulmonary Edema",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "10-01-20",
  },
  "1215": {
    name: "Childbirth Mother",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "1215-P": {
    name: "PChildbirth Mother",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "10-01-24",
  },
  "1216-P": {
    name: "PNewborn Neonatal Resus",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "07-01-24",
  },
  "1217": {
    name: "Pregnancy Complication",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "1217-P": {
    name: "PPregnancy Complication",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "10-01-24",
  },
  "1218": {
    name: "Pregnancy Labor",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-20",
  },
  "1218-P": {
    name: "PPregnancy Labor",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "10-01-24",
  },
  "1219": {
    name: "Allergy",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "1219-P": {
    name: "PAllergy",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "10-10-24",
  },
  "1220": {
    name: "Burns",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "1220-P": {
    name: "PBurns",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "07-01-24",
  },
  "1221": {
    name: "Electrocution",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "1221-P": {
    name: "PElectrocution",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "07-01-24",
  },
  "1222": {
    name: "Hyperthermia Environmental",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "1222-P": {
    name: "PHyperthermia Environmental",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "07-01-24",
  },
  "1223": {
    name: "Hypothermia Cold Injury",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "1223-P": {
    name: "PHypothermia Cold Injury",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "07-01-24",
  },
  "1224": {
    name: "Stings Venomous Bites",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "1224-P": {
    name: "PStings Venomous Bites",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "07-01-24",
  },
  "1225": {
    name: "Submersion",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "1225-P": {
    name: "PSubmersion",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "07-01-24",
  },
  "1226": {
    name: "ENTDental Emergencies",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-20",
  },
  "1226-P": {
    name: "PENTDental Emergencies",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "07-01-20",
  },
  "1228": {
    name: "Eye Problem Unspecified",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-20",
  },
  "1228-P": {
    name: "PEye Problem",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "07-01-20",
  },
  "1229": {
    name: "ALOC",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "1229-P": {
    name: "PALOC",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "07-01-24",
  },
  "1230": {
    name: "Dizziness Vertigo",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "1230-P": {
    name: "PDizziness Vertigo",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "07-01-24",
  },
  "1231": {
    name: "Seizure",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "1231-P": {
    name: "PSeizure",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "07-03-25",
  },
  "1232": {
    name: "Stroke CVATIA",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-25",
  },
  "1232-P": {
    name: "PStroke CVA TIA",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "02-01-22",
  },
  "1233": {
    name: "Syncope / Near Syncope",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "1233-P": {
    name: "PSyncope Near Syncope",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "10-01-24",
  },
  "1234": {
    name: "Airway Obstruction",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-22",
  },
  "1234-P": {
    name: "P Airway Obstruction",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "07-01-22",
  },
  "1235-P": {
    name: "PBRUE",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "07-01-24",
  },
  "1236": {
    name: "Inhalation Injury",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "1236-P": {
    name: "PInhalation Injury",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "04-01-25",
  },
  "1237": {
    name: "Resp Distress",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "1237-P": {
    name: "PRespiratory Distress",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "04-01-25",
  },
  "1238": {
    name: "Carbon Monoxide Poisoning",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "1238-P": {
    name: "PCarbon Monoxide Exposure",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "04-01-25",
  },
  "1239": {
    name: "Dystonic Reaction",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "01-26-21",
  },
  "1239-P": {
    name: "PDystonic Reaction",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "01-26-21",
  },
  "1240": {
    name: "HAZMAT",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "1240-P": {
    name: "PHAZMAT",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "04-01-25",
  },
  "1241": {
    name: "Overdose / Poisoning / Ingestion",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "10-01-24",
  },
  "1241-P": {
    name: "POverdose Poisoning Ingestion",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "10-01-24",
  },
  "1242": {
    name: "Crush Injury",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "1242-P": {
    name: "PCrush Injury Syndrome",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "04-01-25",
  },
  "1243": {
    name: "Traumatic Arrest",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "1243-P": {
    name: "PTraumatic Arrest",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "07-01-24",
  },
  "1244": {
    name: "Traumatic Injury",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "1244-P": {
    name: "PTraumatic Injury",
    category: "treatment_protocol",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "04-01-25",
  },
  "1300": {
    name: "Tableof Contents",
    category: "mcg",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: undefined,
  },
  "1301": {
    name: "Codeof Ethics",
    category: "mcg",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "12-01-23",
  },
  "1302": {
    name: "Airway Management",
    category: "mcg",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "1303": {
    name: "Cath Lab Activation",
    category: "mcg",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-25",
  },
  "1305": {
    name: "Capnography",
    category: "mcg",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: undefined,
  },
  "1306": {
    name: "Evaluation and Care of Patients At Risk of Suicide",
    category: "mcg",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-25",
  },
  "1306.1": {
    name: "Columbia Suicide Severity Risk Scale",
    category: "mcg",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-25",
  },
  "1306.2": {
    name: "Disposition Guidance for Patients at Risk of Suicide",
    category: "mcg",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-25",
  },
  "1307": {
    name: "Care of the Patient with Agitation MCG",
    category: "mcg",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-25",
  },
  "1307.1": {
    name: "Flowchart for Initial Approach to Scene Safety",
    category: "mcg",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-25",
  },
  "1307.2": {
    name: "Verbal De-Escalation",
    category: "mcg",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-25",
  },
  "1307.3": {
    name: "Common Etiologies of Agitation",
    category: "mcg",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-25",
  },
  "1307.4": {
    name: "EMS and Law Enforcement Co-Response",
    category: "mcg",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-25",
  },
  "1308": {
    name: "Cardiac Monitoring and 12 Lead ECG",
    category: "mcg",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "1309": {
    name: "Color Code Drug Doses",
    category: "mcg",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-25",
  },
  "1310": {
    name: "CEW Deployment",
    category: "mcg",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "09-01-19",
  },
  "1315": {
    name: "CPAP",
    category: "mcg",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "06-01-18",
  },
  "1317": {
    name: "Drug Reference",
    category: "mcg",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "1317.1": {
    name: "Adenosine",
    category: "drug_reference",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "1317.3": {
    name: "Albuterol",
    category: "drug_reference",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "1317.5": {
    name: "Amiodarone",
    category: "drug_reference",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "1317.7": {
    name: "Aspirin",
    category: "drug_reference",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "1317.9": {
    name: "Atropine",
    category: "drug_reference",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "1317.11": {
    name: "Calcium Chloride",
    category: "drug_reference",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "10-01-24",
  },
  "1317.13": {
    name: "Dextrose",
    category: "drug_reference",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "1317.15": {
    name: "Diphenhydramine",
    category: "drug_reference",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "1317.17": {
    name: "Epinephrine",
    category: "drug_reference",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "1317.19": {
    name: "Fentanyl",
    category: "drug_reference",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "1317.20": {
    name: "Glucagon",
    category: "drug_reference",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "1317.21": {
    name: "Hydroxocobalamin",
    category: "drug_reference",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "1317.23": {
    name: "Lidocaine",
    category: "drug_reference",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "1317.25": {
    name: "Midazolam",
    category: "drug_reference",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-03-25",
  },
  "1317.27": {
    name: "Morphine",
    category: "drug_reference",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "1317.29": {
    name: "Naloxone",
    category: "drug_reference",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "1317.31": {
    name: "Nitroglycerin",
    category: "drug_reference",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "1317.32": {
    name: "Olanzapine",
    category: "drug_reference",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "1317.33": {
    name: "Ondansetron",
    category: "drug_reference",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "1317.35": {
    name: "Oxygen",
    category: "drug_reference",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "1317.37": {
    name: "Pralidoxime Chloride (2-PAM)",
    category: "drug_reference",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "1317.37-P": {
    name: "Pralidoxime Chloride",
    category: "drug_reference",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "07-01-24",
  },
  "1317.39": {
    name: "Sodium Bicarbonate",
    category: "drug_reference",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "1317.41": {
    name: "TXA",
    category: "drug_reference",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-24",
  },
  "1318": {
    name: "e CPRPatient Algorithm",
    category: "mcg",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-25",
  },
  "1320": {
    name: "LOC",
    category: "mcg",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "06-01-18",
  },
  "1325": {
    name: "MCSDevices",
    category: "mcg",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "09-01-22",
  },
  "1330": {
    name: "Medication Orders Administration",
    category: "mcg",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-2020",
  },
  "1333": {
    name: "Monitoring Transfusionof Blood Products",
    category: "mcg",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "1335": {
    name: "Needle Thoracostomy",
    category: "mcg",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "01-01-25",
  },
  "1337": {
    name: "Naloxone Distribution",
    category: "mcg",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: undefined,
  },
  "1340": {
    name: "Online Medical Control Hospital Notification",
    category: "mcg",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-18",
  },
  "1345-P": {
    name: "Pain Management",
    category: "mcg",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "01-01-25",
  },
  "1350-P": {
    name: "Pediatric Patients",
    category: "mcg",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "10-01-23",
  },
  "1355-P": {
    name: "Perfusion Status",
    category: "mcg",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "10-01-24",
  },
  "1357-P": {
    name: "PPE",
    category: "mcg",
    scope: "Paramedic",
    isPediatric: true,
    revisionDate: "10-01-23",
  },
  "1360": {
    name: "Spinal Motion Restriction",
    category: "mcg",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "12-01-18",
  },
  "1365": {
    name: "TCP",
    category: "mcg",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-24",
  },
  "1370": {
    name: "Traumatic Hemorrhage Control",
    category: "mcg",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "1373": {
    name: "TPQIFallout Data Dictionary",
    category: "mcg",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "07-01-25",
  },
  "1375": {
    name: "Vascular Access",
    category: "mcg",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "04-01-25",
  },
  "1380": {
    name: "Vital Signs",
    category: "mcg",
    scope: "Paramedic",
    isPediatric: false,
    revisionDate: "09-01-21",
  }
} as const;

/**
 * Check if a protocol code is valid in LA County EMS system.
 * @param code - Protocol code (e.g., "1210", "1317.29", "803")
 * @returns true if the protocol exists in LA County PCM
 */
export function isValidProtocol(code: string): boolean {
  // Normalize code (remove "TP ", "Ref ", "MCG " prefixes)
  const normalized = normalizeProtocolCode(code);
  return normalized in LA_COUNTY_PROTOCOLS;
}

/**
 * Get protocol information if valid.
 * @param code - Protocol code
 * @returns Protocol info or null if invalid
 */
export function getProtocol(code: string): LACountyProtocol | null {
  const normalized = normalizeProtocolCode(code);
  return LA_COUNTY_PROTOCOLS[normalized] ?? null;
}

/**
 * Get provider scope for a protocol.
 * @param code - Protocol code
 * @returns "EMT", "Paramedic", "both", or null if invalid
 */
export function getProtocolScope(code: string): ProviderScope | null {
  const protocol = getProtocol(code);
  return protocol?.scope ?? null;
}

/**
 * Validate multiple protocol citations and return invalid ones.
 * @param codes - Array of protocol codes to validate
 * @returns Array of invalid protocol codes
 */
export function findInvalidProtocols(codes: string[]): string[] {
  return codes.filter(code => !isValidProtocol(code));
}

/**
 * Normalize a protocol code by removing common prefixes.
 */
export function normalizeProtocolCode(code: string): string {
  return code
    .replace(/^(TP|Ref\.?|MCG|Reference|Protocol)\s*/i, "")
    .replace(/\s+/g, "")
    .trim();
}

/**
 * Extract all protocol codes from text (for validation).
 */
export function extractProtocolCodes(text: string): string[] {
  const patterns = [
    /\b(1[0-2]\d{2}(?:\.\d+)?(?:-P)?)\b/g,  // Treatment protocols
    /\b(13\d{2}(?:\.\d+)?)\b/g,              // MCG
    /\b([2-8]\d{2}(?:\.\d+)?)\b/g,           // Policies
    /(?:TP|Ref|MCG|Protocol)\s*(\d{3,4}(?:\.\d+)?)/gi,
  ];

  const codes = new Set<string>();
  for (const pattern of patterns) {
    let match;
    while ((match = pattern.exec(text)) !== null) {
      codes.add(match[1]);
    }
  }

  return Array.from(codes);
}

// Export count for validation
export const PROTOCOL_COUNT = 291;
